# Use official OpenJDK 17 image as the base image
FROM eclipse-temurin:17-alpine

RUN addgroup -S paymentchain && adduser -S admin -G paymentchain
USER admin:paymentchain
VOLUME /tmp
# Copiamos el jar a la imagen
ARG JAR_FILE
ADD ${JAR_FILE} app.jar
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]